---

- name: Download web
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  tags: without-postgres

#   yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
#   yum install -y postgresql14-server
#   /usr/pgsql-14/bin/initdb -D /var/lib/pgsql/14/data
#   mkdir /wal
#   chown -R postgres.postgres /wal
#   chown -R postgres.postgres /var/lib/pgsql/14/data
#--------------------------Занести эти строки в файл pg_hba.conf
#   host replication  all 192.168.14.0/24  trust
#----------------------------
#-----------------------------Занести эти строки в файл postgresql.conf
#    listen_addresses = '*' 
#    wal_level = 'replica' 
#    archive_mode = on 
#    archive_command = 'test ! -f /wal/%f && cp %p /wal/%f'
#-------------------------------------------
#   systemctl reload postgresql-14.service
#   su - root
#   su - postgres
#   psql


- name: groupinstall
  shell: 'yum groupinstall -y "Development Tools"'

- name: Install python3-devel
  yum: 
    name:
      - python3-devel
    state: installed
  ignore_errors: yes


- name: Install postgresql-libs
  yum: 
    name:
      - postgresql-libs
    state: installed
  ignore_errors: yes

- name: Install postgresql-devel
  yum: 
    name:
      - postgresql-devel
    state: installed
  ignore_errors: yes
  
- name: Install postgresql-devel
  yum: 
    name:
      - python2-psycopg2
      # - python3-psycorg2
    state: present
  ignore_errors: yes



- name: Install pgsql
  yum:
    name: postgresql14-server
  tags: postgres

# - name: Ensure PostgreSQL database is initialized.
#   shell: "/usr/pgsql-14/bin/initdb -D /var/lib/pgsql/14/data"
- name: check initialization db
  stat:
    path: "/var/lib/pgsql/14/data/postgresql.conf"
  register: stat_result
  tags: check-init

- name: initialize db
  become_user: postgres
  shell: "/usr/pgsql-14/bin/initdb -D /var/lib/pgsql/14/data/"
  become_user: postgres
  become: yes
  when: not stat_result.stat.exists
  tags: init

- name: WAL
  file: path=/wal state=directory owner=postgres group=postgres

- name: MODE-wal
  ansible.builtin.file:
    path: /wal
    state: directory
    recurse: yes
    owner: postgres
    group: postgres


- name: MODE-var/lib/pgsql
  ansible.builtin.file:
    path: /var/lib/pgsql/14/data
    state: directory
    recurse: yes
    owner: postgres
    group: postgres

# - name: Pg_hba-config
#   community.postgresql.postgresql_pg_hba:
#     dest: /var/lib/pgsql/14/data/pg_hba.conf
#     contype: host
#     users: replication
#     source: 192.168.14.0/24
#     databases: all
#     method: trust
#   notify:
#     - restart postgres 
#   tags: pg_hba

- name: delete file pg_hba.conf
  ansible.builtin.file:
    path: /var/lib/pgsql/14/data/pg_hba.conf
    state: absent
  tags: delete

- name: delete file postgresql
  ansible.builtin.file:
    path: /var/lib/pgsql/14/data/postgresql.conf
    state: absent
  tags: delete


- name: pg_hba.config
  ansible.builtin.file:
    src: pg_hba.conf
    dest: /var/lib/pgsql/14/data/pg_hba.conf
    owner: postgres
    group: postgres
    state: touch
  # notify:
  #   - restart postgres
  tags: pg_hba

    
- name: postgres-config
  ansible.builtin.file:
    src: postgresql.conf
    dest: /var/lib/pgsql/14/data/postgresql.conf
    owner: postgres
    group: postgres
    state: touch
  # notify:
  #   - restart postgres 
  tags: postgresql

- name: Start config
  systemd:
    name: postgresql-14.service
    state: restarted
    enabled: yes

#community.postgresql

- name: create ROLE replicant
  postgresql_user:
    db: postgres
    login_unix_socket: /var/run/postgresql
    name: replicant
    password: replicant
    role_attr_flags: LOGIN,REPLICATION
  become_user: postgres
  become: yes
  ignore_errors: yes

