- hosts: consul
  become: yes
  roles:
    - role: consul
      vars:
        dc_name: "depplum"
        consul_ansible_group: "consul"
        
- name: psql
  hosts: postgres
  become: true
  strategy: linear
  roles:
    - clients
    
- name: nfs
  hosts: ip_nfs
  become: true
  strategy: linear
  roles:
    - nfs
